### ISSUE TITLE
Error in console when starting a game with a party

### ISSUE THREAD

**Issue by JorisvD01** [dumbo-the-developer/Duels#102]
### Server version

Paper version 1.21.1-132-ver/1.21.1@b48403b

### Duels version

2.9

### Plugin list

![Image](https://github.com/user-attachments/assets/3cfcc67f-2372-4ad2-8d05-3930769faa03)

### Describe the bug

Whenever 2 parties join the queue, they leaders get messages the opponent is found and the match is starting, but the match doesn't actually start and the message keeps repeating itself

![Image](https://github.com/user-attachments/assets/b3575a20-7032-46c7-a9e3-2bc909aba6c1)

Along with this the following error also gets sent in console every time the users get the message;
[20:55:41 WARN]: [Duels] Task #129 for Duels v2.8 generated an exception
java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "com.meteordevelopments.duels.setting.Settings.getSenderParty()" is null
at Duels-Optimised-2.8.jar/com.meteordevelopments.duels.duel.DuelManager.startMatch(DuelManager.java:319) ~[Duels-Optimised-2.8.jar:?]
at Duels-Optimised-2.8.jar/com.meteordevelopments.duels.queue.QueueManager.lambda$handleLoad$1(QueueManager.java:184) ~[Duels-Optimised-2.8.jar:?]
at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

Party config:
```
party:
  # Party invite expiration, in seconds.
  # default: 30
  invite-expiration: 30

  # If the party owner is offline for the time (in minutes) specified below, the party will be automatically disbanded. Set to -1 to disable.
  # default: 10
  auto-disband-after: 5

  # The max size a party can have.
  # default: 10
  max-size: 3

  # If set to 'true', only parties that are equally sized may duel each other.
  # default: true
  same-size-only: true
```

### Expected behavior

The match should start with both parties

### Steps to reproduce

1. Install plugin.
2. Setup as described above
3. Get 2 parties of 2 players
4. start match thru a queue
5. Issue occurs

### Checklist

- [x] I am running latest version of the plugin
- [x] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [x] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [x] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds
