### ISSUE TITLE
Players kicked from queue if multiple party sizes are queued.

### ISSUE THREAD

**Issue by JorisvD01** [dumbo-the-developer/Duels#103]
### Server version

Paper version 1.21.1-132-ver/1.21.1@b48403b

### Duels version

2.8

### Plugin list

![Image](https://github.com/user-attachments/assets/80c0285e-6281-4c03-9bd6-26f80ce16aa4)

### Describe the bug

Whenever 2 different size parties join the queue, all users get the following message:

![Image](https://github.com/user-attachments/assets/984ef675-fe25-48db-af18-265130f935a1)

Instead of waiting for the next valid opponent that matches the right party size, it kicks both users from the queue. This way the user's can't really wait for a valid opponent party with the right size.

In the config 'same-size-only` is set to true.

Party config
```
party:
  # Party invite expiration, in seconds.
  # default: 30
  invite-expiration: 30

  # If the party owner is offline for the time (in minutes) specified below, the party will be automatically disbanded. Set to -1 to disable.
  # default: 10
  auto-disband-after: 5

  # The max size a party can have.
  # default: 10
  max-size: 3

  # If set to 'true', only parties that are equally sized may duel each other.
  # default: true
  same-size-only: true
```

### Expected behavior

Both parties remain in queue to wait for the next opponent of the right partysize, while not getting any messages / interference with parties of other sizes

### Steps to reproduce

1. Install plugin
2. Set same-size-only to true
3. Join a queue with a solo player, and a party of 2 or more
4. Issue occurs

### Checklist

- [x] I am running latest version of the plugin
- [x] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [x] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [x] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds
