### ISSUE TITLE
end-commands aren't executed when /duels reload is executed and possibly server closed

### ISSUE THREAD

**Issue by bobhenl** [dumbo-the-developer/Duels#61]
### Server version

Purpur 1.21.1

### Duels version

1.9

### Plugin list

[07:48:52 INFO]: Paper Plugins: (2):
[07:48:52 INFO]:  - EconomyShopGUI-Premium, EconomyShopGUI-Premium
[07:48:52 INFO]: Bukkit Plugins: (143):
[07:48:52 INFO]:  - AdvancedEnderchest, AdvancedReplay, ajLeaderboards, ajParkour, AmazingTitles, AngleGuard, AntiAura-ESP, AntiCheatReplay, AutoSmelt, BattlePass
[07:48:52 INFO]:  BestTools, BetterBlocks, BetterBlocksLib, BetterRTP, Boatglitchprevent, BottledExp, ChatControlRed, ChatEmojis, ChatPlayPlugin, ChestPreview
[07:48:52 INFO]:  ChestSort, Citizens, CMI, CMILib, CommandAPI, CommandBridge, ConsoleSpamFix, CoreProtect, CrazyEnvoys, CrazyVouchers
[07:48:52 INFO]:  CustomPlaceholders, DecentHolograms, DeluxeCoinflip, DeluxeCombat, DeluxeMenus, DisableSignEdit, DiscordChangelog, DiscordSRV, DragonSlayer, DragonTimer
[07:48:52 INFO]:  Drop2InventoryPlus, Duels, dynmap, EmailerContinued, EntitySize, EternalTags, ExtraContexts, Factions, FancyPhysics, FastAsyncWorldEdit
[07:48:52 INFO]:  FasterCrystals, FileCleaner, floodgate, ForcePack, GadgetsMenu, GeoTebexCoupons, GrapplingHook, GSit, HeadDatabase, HoloMobHealth
[07:48:52 INFO]:  HubPvP, IllegalStack, ImageFireworksPro, ImageFrame, InteractionVisualizer, InteractiveChat, InteractiveChatDiscordSrvAddon, InventoryRollbackPlus, InvUnload, ItemPrices
[07:48:52 INFO]:  ItemsAdder, JumpPads, LagAssist, Lib1711, LibsDisguises, LifeStealZ, LiteBans, LoneLibs, LuckPerms, MineXFarmRegen
[07:48:52 INFO]:  MobFarmManager, MoneyFromMobs, MoneyPouchDeluxe, Multiverse-Core, NBTAPI, NetworkInterceptor, nightcore, *NightVision, NPCReplay, packetevents
[07:48:52 INFO]:  PhysicsToGo, Pl-Hide-Pro, PlaceholderAPI, Plan, PlayerPoints, PlugManX, Polymart, ProtocolLib, pvpstats, RawMsg
[07:48:52 INFO]:  Referral, RegionPlaceholder, SecureBeds, SecureStorage, SelectionVisualizer, SkinsRestorer, SmoothSleep, SnowballEffect, SpawnerMeta, SpecializedCrates
[07:48:52 INFO]:  StoreStats, StreamingDrops, StreamSpectate, SurveyPlus, TAB, Tebex, TheCore, Themis, ThrowableSpawnEggs, ToastedAFK
[07:48:52 INFO]:  TradeMe, TrailGUI, TryMe, UIFramework, UltimateContent, UltraCosmetics, Vault, Vegas, VeinMiner, ViaBackwards
[07:48:52 INFO]:  ViaRewind, ViaVersion, ViaVersionStatus, VillagerMarket, VoidTeleportPlus, Votifier, Voting, VotingPlugin, Vulcan, WorldGuard
[07:48:52 INFO]:  WorldGuardExtraFlags, zAuctionHouseV3, zMenu

### Describe the bug

Hello, so there's end-command section in the config:
```yml
    end-commands:
      # If set to 'true', the commands listed below will run at the end of a match.
      # default: false
      enabled: true

      # If set to 'true', end commands will run only for matches started through the queue system.
      # default: false
      queue-matches-only: false

      # Available placeholders:
      # %winner% - Name of the winner of the match
      # %loser% - Name of the loser of the match
      commands:
#        - 'heartsback %loser%'
#        - 'heartsback %winner%'
        - 'effect clear %winner% -s'
        - 'effect clear %loser% -s'
        - 'resetback %winner% -s -death'
        - 'resetback %loser% -s -death'
        - 'duelsregionremove %winner% %loser%'
```

and these commands aren't executed when players are kicked from the arena on /duels reload, and possibly on the server restart, too. Which is a big issue in case I return them hearts, clear effects, resetback & remove them from regions.

### Expected behavior

Executing this section on reload & when stopping the plugin.

### Steps to reproduce

1. List some commands to end-commands in config, that you can test.
2. Now duel and normally kill the player and test that commands are executed
3. If so, now duel again but now do /duel reload from console, and you'll see that they aren't executed, even when you get kicked from duel

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds
